connection:
  host: "127.0.0.1:2775"
  login: foo
  password: password
  bind_timout_ms: 3000
  bind_type: transmitter # transmitter, transceiver
  window_size: 20
  response_timeout_ms: 10000

message:
  phone_country: RU
  source: VIRTA
  random: false
  text: "hello world"

logger:
  enabled: true
  filename: 'bench.log'
  level: debug

benchmark:
  initial_rps: 10
  max_rps: 1000
  factor: 1.5
  burst_percentage: 0.1
  output_tick_interval_ms: 3000