connection:
  host: "127.0.0.1:2775"
  login: foo
  password: password
  window_size: 20
  bind_timout_ms: 3000
  bind_type: transceiver # transmitter, transceiver

message:
  phone_country: RU
  source: VIRTA
  random: false
  text: "hello world"

logger:
  enabled: true
  filename: 'bench.log'
  level: debug

benchmark:
  initial_rps: 10
  max_rps: 1000
  factor: 1.5
  burst_percentage: 0.1
  output_tick_interval_ms: 3000